const dataBase = [
  {
    name: "Mercedes Benz",
    brand: "Mercedes",
    brandImage: "/assets/svg/Mercedes.svg",
    generations: [
      {
        class: "A class",
        type: "compact hatchback and sedan",
        carModels: [
          {
            carModelName: "A 180",
            engineType: "1.3 liter turbo engine",
            power: "136 horsepower",
            acceleration: "100km/h: 8.5 seconds",
            carPrice: 34000,
          },
          {
            carModelName: "A 200",
            engineType: "1.3 liter turbo engine",
            power: "163 horsepower",
            acceleration: "100km/h: 8.0 seconds",
            carPrice: 36000,
          },
          {
            carModelName: "A 220",
            engineType: "2.0 liter turbo engine",
            power: "188 horsepower",
            acceleration: "100km/h: 6.2 seconds",
            carPrice: 38000,
          },
          {
            carModelName: "A 250",
            engineType: "2.0 liter turbo engine",
            power: "221 horsepower",
            acceleration: "100km/h: 6.0 seconds",
            carPrice: 42000,
          },
          {
            carModelName: "A 35 AMG",
            engineType: "2.0 liter turbo engine",
            power: "302 horsepower",
            acceleration: "100km/h: 4.7 seconds",
            carPrice: 45000,
          },
          {
            carModelName: "A 45 AMG",
            engineType: "2.0 liter turbo engine",
            power: "382 horsepower",
            acceleration: "100km/h: 3.9 seconds",
            carPrice: 57000,
          },
        ],
      },
      {
        class: "B class",
        type: "compact MPV",
        carModels: [
          {
            carModelName: "B 180",
            engineType: "1.3 liter turbo engine",
            power: "136 horsepower",
            acceleration: "100km/h: 9.0 seconds",
            carPrice: 36000,
          },
          {
            carModelName: "B 200",
            engineType: "1.3 liter turbo engine",
            power: "163 horsepower",
            acceleration: "100km/h: 8.0 seconds",
            carPrice: 38000,
          },
          {
            carModelName: "B 250",
            engineType: "2.0 liter turbo engine",
            power: "224 horsepower",
            acceleration: "100km/h: 6.9 seconds",
            carPrice: 40000,
          },
        ],
      },
      {
        class: "C class",
        type: "sports sedan and coupe",
        carModels: [
          {
            carModelName: "C 180",
            engineType: "1.5 liter turbo engine",
            power: "156 horsepower",
            acceleration: "100km/h: 8.6 seconds",
            carPrice: 43000,
          },
          {
            carModelName: "C 200",
            engineType: "2.0 liter turbo engine",
            power: "204 horsepower",
            acceleration: "100km/h: 7.5 seconds",
            carPrice: 46000,
          },
          {
            carModelName: "C 300",
            engineType: "2.0 liter turbo engine",
            power: "258 horsepower",
            acceleration: "100km/h: 5.9 seconds",
            carPrice: 50000,
          },
          {
            carModelName: "C 43 AMG",
            engineType: "3.0 liter V6 turbo twin",
            power: "385 horsepower",
            acceleration: "100km/h: 4.6 seconds",
            carPrice: 64000,
          },
          {
            carModelName: "C 63 AMG",
            engineType: "4.0 liter V8 turbo twin",
            power: "469-503 horsepower",
            acceleration: "100km/h: 4.0 seconds",
            carPrice: 73000,
          },
        ],
      },
      {
        class: "E class",
        type: "high-end luxury sedan",
        carModels: [
          {
            carModelName: "E 200",
            engineType: "2.0 liter turbo engine",
            power: "197 horsepower",
            acceleration: "100km/h: 7.4 seconds",
            carPrice: 56000,
          },
          {
            carModelName: "E 220d",
            engineType: "2.0 liter turbo engine",
            power: "194 horsepower",
            acceleration: "100km/h: 7.5 seconds",
            carPrice: 58000,
          },
          {
            carModelName: "E 300",
            engineType: "2.0 liter turbo engine",
            power: "258 horsepower",
            acceleration: "100km/h: 5.9 seconds",
            carPrice: 63000,
          },
          {
            carModelName: "E 350e",
            engineType: "Hibrid",
            power: "300 horsepower",
            acceleration: "100km/h: 5.5 seconds",
            carPrice: 70000,
          },
          {
            carModelName: "E 43 AMG",
            engineType: "3.0 liter V6 turbo twin",
            power: "396 horsepower",
            acceleration: "100km/h: 4.5 seconds",
            carPrice: 79000,
          },
          {
            carModelName: "E 63 AMG",
            engineType: "4.0 liter turbo engine",
            power: "603 horsepower",
            acceleration: "100km/h: 3.3 seconds",
            carPrice: 104000,
          },
        ],
      },
      {
        class: "S class",
        type: "flagman Lucs sedan",
        carModels: [
          {
            carModelName: "E 200",
            engineType: "2.0 liter turbo engine",
            power: "197 horsepower",
            acceleration: "100km/h: 7.4 seconds",
            carPrice: 56000,
          },
          {
            carModelName: "E 220d",
            engineType: "2.0 liter turbo engine",
            power: "194 horsepower",
            acceleration: "100km/h: 7.5 seconds",
            carPrice: 58000,
          },
          {
            carModelName: "E 300",
            engineType: "2.0 liter turbo engine",
            power: "258 horsepower",
            acceleration: "100km/h: 5.9 seconds",
            carPrice: 63000,
          },
          {
            carModelName: "E 350e",
            engineType: "Hibrid",
            power: "300 horsepower",
            acceleration: "100km/h: 5.5 seconds",
            carPrice: 70000,
          },
          {
            carModelName: "E 43 AMG",
            engineType: "3.0 liter V6 turbo twin",
            power: "396 horsepower",
            acceleration: "100km/h: 4.5 seconds",
            carPrice: 79000,
          },
          {
            carModelName: "E 63 AMG",
            engineType: "4.0 liter turbo engine",
            power: "603 horsepower",
            acceleration: "100km/h: 3.3 seconds",
            carPrice: 104000,
          },
        ],
      },
    ],
  },
  {
    name: "Bayerische Motoren Werke",
    brand: "BMW",
    brandImage: "/assets/svg/bmw.svg",
    generations: [
      {
        class: "BMW M",
        carModels: [
          {
            carModelName: "M1",
            engineType: "1.3 liter turbo engine",
            power: "136 horsepower",
            acceleration: "100km/h: 8.5 seconds",
            carPrice: 34000,
          },
        ],
      },
    ],
  },
  {
    name: "Ford",
    brand: "Ford",
    brandImage: "/assets/svg/ford.svg",
  },
  {
    name: "Bugatti",
    brand: "Bugatti",
    brandImage: "/assets/svg/bugatti.svg",
  },
];
